import { SideNavInterface } from '@app/@layout/backend/side-nav.type';
import { PermissionKey as PK } from '@app/@shared/@types/permission';

export const MENU: SideNavInterface[] | any = [
  {
    path: 'dashboard',
    title: 'menu.dashboard',
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'home',
    submenu: [],
  },
  {
    path: 'patient-dashboard',
    title: 'menu.dashboard',
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'home',
    submenu: [],
  },
  {
    path: 'case-management',
    title: 'menu.caseManagement',
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'audit',
    permissions: [PK.PATIENTS_VIEW_DEPARTMENT, PK.PATIENTS_EDIT_DEPARTMENT],
    submenu: [
      {
        path: 'case-management/patients',
        title: 'menu.patients',
        iconType: '',
        iconTheme: '',
        permissions: [PK.PATIENTS_VIEW_DEPARTMENT],
        submenu: [],
      },
      {
        path: 'case-management/caregiver-list',
        title: 'menu.caregivers',
        iconType: '',
        iconTheme: '',
        permissions: [PK.PATIENTS_VIEW_DEPARTMENT],
        submenu: [],
      },
      {
        path: 'user-management/therapists',
        title: 'menu.therapists',
        iconType: '',
        iconTheme: '',
        permissions: [PK.USERS_VIEW_DEPARTMENT],
        submenu: [],
      },
      {
        path: 'user-management/supervisors',
        title: 'menu.supervisors',
        iconType: '',
        iconTheme: '',
        permissions: [PK.USERS_VIEW_DEPARTMENT],
        submenu: [],
      },
    ],
  },
  {
    path: 'assessments',
    title: 'menu.evaluationManagement',
    permissions: [PK.ASSESSMENTS_VIEW_DEPARTMENT, PK.ASSESSMENTS_EDIT_DEPARTMENT, PK.QUESTIONNAIRES_VIEW_DEPARTMENT, PK.QUESTIONNAIRES_EDIT_DEPARTMENT],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'edit',
    submenu: [
      {
        path: 'assessments',
        title: 'menu.assessments',
        permissions: [PK.ASSESSMENTS_VIEW_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'questionnaire-management/questionnaire-list',
        title: 'menu.questionnaires',
        permissions: [PK.QUESTIONNAIRES_VIEW_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'questionnaire-management/questionnaire-bundles-list',
        title: 'menu.questionnaireBundles',
        permissions: [PK.QUESTIONNAIRES_EDIT_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'evaluation-schemes',
        title: 'menu.evaluationSchemes',
        permissions: [PK.ASSESSMENTS_VIEW_DEPARTMENT, PK.ASSESSMENTS_EDIT_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'randomizations',
        title: 'menu.randomizations',
        permissions: [PK.ASSESSMENTS_VIEW_DEPARTMENT, PK.ASSESSMENTS_EDIT_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'evaluation-automations',
        title: 'menu.evaluationAutomations',
        permissions: [
          PK.AUTOMATIONS_VIEW_DEPARTMENT,
          PK.AUTOMATIONS_VIEW_ALL,
          PK.AUTOMATIONS_EDIT_DEPARTMENT,
          PK.AUTOMATIONS_EDIT_ALL,
        ],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'user-management',
    title: 'menu.userManagement',
    permissions: [PK.USERS_VIEW_DEPARTMENT, PK.USERS_EDIT_DEPARTMENT],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'user',
    submenu: [
      {
        path: 'user-management/users',
        title: 'menu.listUsers',
        permissions: [PK.USERS_VIEW_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'user-management/user-form',
        title: 'menu.newUser',
        permissions: [PK.USERS_EDIT_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'administration',
    title: 'menu.administration',
    permissions: [PK.ROLES_VIEW_ALL, PK.SETTINGS_VIEW_ALL, PK.SYSTEM_VIEW_ALL],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'setting',
    submenu: [
      {
        path: 'administration/reports',
        title: 'menu.reports',
        permissions: [PK.REPORTS_VIEW_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/permission-matrix',
        title: 'menu.permissionMatrix',
        permissions: [PK.ROLES_VIEW_ALL],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/roles',
        title: 'menu.roles',
        permissions: [PK.ROLES_VIEW_ALL],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/departments',
        title: 'menu.departments',
        permissions: [PK.SETTINGS_VIEW_ALL],
        iconType: '',
        iconTheme: '',
        icon: '',
        submenu: [],
      },
      {
        path: 'administration/disclaimers',
        title: 'menu.disclaimers',
        permissions: [PK.SETTINGS_VIEW_ALL],
        iconType: '',
        iconTheme: '',
        icon: '',
        submenu: [],
      },
      {
        path: 'administration/assessments',
        title: 'menu.assessments',
        permissions: [PK.SETTINGS_VIEW_ALL],
        iconType: '',
        iconTheme: '',
        icon: '',
        submenu: [],
      },
      {
        path: 'administration/patient-statuses',
        title: 'menu.patientStatuses',
        permissions: [PK.SETTINGS_VIEW_ALL],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/version',
        title: 'menu.version',
        permissions: [PK.SETTINGS_VIEW_ALL],
        iconType: 'nzIcon',
        iconTheme: 'outline',
        icon: 'code',
        submenu: [],
      },
      {
        path: 'administration/settings',
        title: 'menu.settings',
        permissions: [PK.SETTINGS_VIEW_ALL, PK.SYSTEM_VIEW_ALL],
        iconType: '',
        iconTheme: '',
        submenu: [
          {
            path: 'administration/settings/system-configuration',
            title: 'menu.systemConfiguration',
            permissions: [PK.SYSTEM_VIEW_ALL],
            iconType: '',
            iconTheme: '',
            submenu: [],
          },
          {
            path: 'administration/settings/follow-up-settings',
            title: 'clinicalSettings.title',
            permissions: [PK.SETTINGS_VIEW_ALL],
            iconType: '',
            iconTheme: '',
            submenu: [],
          },
          {
            path: 'administration/settings/session-cancellation-reasons',
            title: 'menu.reasonConfiguration',
            permissions: [PK.SETTINGS_VIEW_ALL],
            iconType: '',
            iconTheme: '',
            submenu: [],
          },
          {
            path: 'administration/settings/language',
            title: 'menu.language',
            permissions: [PK.SETTINGS_VIEW_ALL],
            iconType: '',
            iconTheme: '',
            submenu: [],
          },
        ],
      },
    ],
  },
  {
    path: 'notifications',
    title: 'menu.notifications',
    permissions: [
      PK.NOTIFICATIONS_VIEW_DEPARTMENT,
      PK.NOTIFICATIONS_EDIT_DEPARTMENT,
      PK.MAIL_TEMPLATES_VIEW_DEPARTMENT,
      PK.MAIL_TEMPLATES_EDIT_DEPARTMENT,
    ],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'bell',
    submenu: [
      {
        path: 'notifications/email-templates',
        title: 'menu.emailTemplates',
        permissions: [PK.MAIL_TEMPLATES_VIEW_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'notifications/administration',
        title: 'menu.notificationAdministration',
        permissions: [PK.NOTIFICATIONS_VIEW_DEPARTMENT, PK.NOTIFICATIONS_EDIT_DEPARTMENT, PK.MAIL_TEMPLATES_VIEW_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'informed-consent',
    title: 'menu.informedConsent',
    permissions: [
      PK.INFORMED_CONSENT_MODELS_VIEW_DEPARTMENT,
      PK.INFORMED_CONSENT_MODELS_EDIT_DEPARTMENT,
      PK.INFORMED_CONSENT_MANAGEMENT_VIEW_DEPARTMENT,
      PK.INFORMED_CONSENT_MANAGEMENT_EDIT_DEPARTMENT,
      PK.INFORMED_CONSENT_RESPONSES_VIEW_DEPARTMENT,
    ],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'file-protect',
    submenu: [
      {
        path: 'informed-consent/models',
        title: 'menu.informedConsentModels',
        permissions: [PK.INFORMED_CONSENT_MODELS_VIEW_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'informed-consent/management',
        title: 'menu.informedConsentManagement',
        permissions: [PK.INFORMED_CONSENT_MANAGEMENT_VIEW_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'informed-consent/responses',
        title: 'menu.informedConsentResponses',
        permissions: [PK.INFORMED_CONSENT_RESPONSES_VIEW_DEPARTMENT],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
];
