import { Form } from '@shared/components/form/@types/form';

export const DepartmentForm: Form = {
  submitButtonText: 'Create Department',
  editButtonText: 'Edit Department',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'Department Name',
          label: 'Department Name',
          description: 'enter permission name',
          translationPath: 'tables.department.departmentName',
          type: 'text',
          validationMessage: 'please enter permission name',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'description',
          title: 'description',
          label: 'Description',
          description: '',
          translationPath: 'tables.department.description',
          type: 'text',
          validationMessage: '',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'active',
          title: 'Status',
          label: 'Status',
          description: '',
          translationPath: 'tables.department.status',
          type: 'select',
          validationMessage: '',
          isRequired: false,
          span: 24,
          options: [
            { label: 'Active', value: true },
            { label: 'Inactive', value: false },
          ],
        },
        {
          value: [],
          name: 'appliedRoleCodes',
          title: 'Aplica a roles',
          label: 'Aplica a roles',
          description: 'Seleccionar roles',
          type: 'select',
          mode: 'multiple',
          validationMessage: 'Seleccione al menos un rol',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: [],
          name: 'defaultRoleCodes',
          title: 'Por defecto para roles',
          label: 'Por defecto para roles',
          description: 'Seleccionar roles',
          type: 'select',
          mode: 'multiple',
          validationMessage: '',
          isRequired: false,
          span: 24,
          options: [],
        },
      ],
    },
  ],
};
