import { Form } from '@shared/components/form/@types/form';

export const DepartmentForm: Form = {
  submitButtonText: 'departments.createDepartment',
  editButtonText: 'departments.editDepartment',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'tables.department.departmentName',
          label: 'tables.department.departmentName',
          description: 'departments.departmentNameDescription',
          translationPath: 'tables.department.departmentName',
          type: 'text',
          validationMessage: 'departments.departmentNameValidation',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'description',
          title: 'tables.department.description',
          label: 'tables.department.description',
          description: '',
          translationPath: 'tables.department.description',
          type: 'text',
          validationMessage: '',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'active',
          title: 'tables.department.status',
          label: 'tables.department.status',
          description: '',
          translationPath: 'tables.department.status',
          type: 'select',
          validationMessage: '',
          isRequired: false,
          span: 24,
          options: [
            { label: 'core.active', value: true },
            { label: 'core.inactive', value: false },
          ],
        },
        {
          value: [],
          name: 'appliedRoleCodes',
          title: 'departments.appliesToRoles',
          label: 'departments.appliesToRoles',
          description: 'departments.selectRoles',
          type: 'select',
          mode: 'multiple',
          validationMessage: 'departments.selectAtLeastOneRole',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: [],
          name: 'defaultRoleCodes',
          title: 'departments.defaultForRoles',
          label: 'departments.defaultForRoles',
          description: 'departments.selectRoles',
          type: 'select',
          mode: 'multiple',
          validationMessage: '',
          isRequired: false,
          span: 24,
          options: [],
        },
      ],
    },
  ],
};
