import { Form } from '../../../@shared/components/form/@types/form';

export const ReportForm: Form = {
  submitButtonText: 'reports.saveReport',
  editButtonText: 'reports.editReport',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'forms.createReportForm.reportName',
          label: 'forms.createReportForm.reportName',
          translationPath: 'forms.createReportForm.reportName',
          description: 'forms.createReportForm.reportNameDescription',
          type: 'text',
          validationMessage: 'forms.createReportForm.reportNameValidation',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'resources',
          title: 'forms.createReportForm.resources',
          label: 'forms.createReportForm.resources',
          translationPath: 'forms.createReportForm.resources',
          description: 'forms.createReportForm.resourcesDescription',
          type: 'select',
          options: [
            { label: 'menu.patients', value: 'Patients' },
            { label: 'menu.therapists', value: 'Therapists' },
            { label: 'menu.supervisors', value: 'Supervisors' },
            { label: 'menu.listUsers', value: 'Users' },
            { label: 'menu.dashboard', value: 'Dashboard' },
          ],
          validationMessage: 'forms.createReportForm.resourcesValidation',
          isRequired: true,
          disabled: false,
          span: 24,
        },
        {
          value: '',
          name: 'description',
          title: 'forms.createReportForm.description',
          label: 'forms.createReportForm.description',
          translationPath: 'forms.createReportForm.description',
          description: 'forms.createReportForm.descriptionDescription',
          type: 'textArea',
          validationMessage: 'forms.createReportForm.descriptionValidation',
          isRequired: true,
          span: 24,
        },
        {
          value: '',
          name: 'appName',
          title: 'forms.createReportForm.appName',
          label: 'forms.createReportForm.appName',
          translationPath: 'forms.createReportForm.appName',
          description: 'forms.createReportForm.appNameDescription',
          type: 'select',
          options: [],
          validationMessage: 'forms.createReportForm.appNameValidation',
          isRequired: true,
          disabled: false,
          span: 24,
        },
        {
          value: '',
          name: 'url',
          title: 'forms.createReportForm.url',
          label: 'forms.createReportForm.url',
          translationPath: 'forms.createReportForm.url',
          description: 'forms.createReportForm.urlDescription',
          type: 'text',
          validationMessage: 'forms.createReportForm.urlValidation',
          isRequired: false,
          disabled: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'repositoryLink',
          title: 'forms.createReportForm.repositoryLink',
          label: 'forms.createReportForm.repositoryLink',
          translationPath: 'forms.createReportForm.repositoryLink',
          description: 'forms.createReportForm.repositoryLinkDescription',
          type: 'text',
          validationMessage: 'forms.createReportForm.repositoryLinkValidation',
          isRequired: false,
          disabled: false,
          span: 24,
          options: [],
        },
        {
          value: false,
          name: 'status',
          title: 'forms.createReportForm.reportStatus',
          label: 'forms.createReportForm.reportStatus',
          translationPath: 'forms.createReportForm.reportStatus',
          description: 'forms.createReportForm.reportStatusDescription',
          type: 'radio',
          options: [
            { label: 'core.on', value: true },
            { label: 'core.off', value: false },
          ],
          validationMessage: 'forms.createReportForm.reportStatusValidation',
          isRequired: false,
          disabled: false,
          span: 24,
        },
      ],
    },
  ],
};
