import { Form } from '../../../@shared/components/form/@types/form';

export const ReportForm: Form = {
  submitButtonText: 'Save Report',
  editButtonText: 'Edit Report',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'Report Name',
          label: 'Report Name',
          translationPath: 'forms.createReportForm.reportName',
          description: 'Enter report name',
          type: 'text',
          validationMessage: 'Please enter report name',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'resources',
          title: 'Report resources',
          label: 'Report resources',
          translationPath: 'forms.createReportForm.resources',
          description: 'Enter Report resources',
          type: 'select',
          options: [
            { label: 'Patients', value: 'Patients' },
            { label: 'Therapists', value: 'Therapists' },
            { label: 'Supervisors', value: 'Supervisors' },
            { label: 'Usuarios', value: 'Users' },
            { label: 'Dashboard', value: 'Dashboard' },
          ],
          validationMessage: 'please Enter Report resources',
          isRequired: true,
          disabled: false,
          span: 24,
        },
        {
          value: '',
          name: 'description',
          title: 'Report description',
          label: 'Report description',
          translationPath: 'forms.createReportForm.description',
          description: 'Enter Report description',
          type: 'textArea',
          validationMessage: 'Please enter report description',
          isRequired: true,
          span: 24,
        },
        {
          value: '',
          name: 'appName',
          title: 'Shiny app',
          label: 'Shiny app',
          translationPath: 'forms.createReportForm.appName',
          description: 'Select Shiny app',
          type: 'select',
          options: [],
          validationMessage: 'Please select a Shiny app',
          isRequired: true,
          disabled: false,
          span: 24,
        },
        {
          value: '',
          name: 'url',
          title: 'Report URL',
          label: 'Report URL',
          translationPath: 'forms.createReportForm.url',
          description: 'Derived from selected Shiny app',
          type: 'text',
          validationMessage: 'Please enter Report URL',
          isRequired: false,
          disabled: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'repositoryLink',
          title: 'Report repository link',
          label: 'Report repository link',
          translationPath: 'forms.createReportForm.repositoryLink',
          description: 'Enter Report repository link',
          type: 'text',
          validationMessage: 'Please enter Report repository link',
          isRequired: false,
          disabled: false,
          span: 24,
          options: [],
        },
        {
          value: false,
          name: 'status',
          title: 'Report repository status',
          label: 'Report repository status',
          translationPath: 'forms.createReportForm.reportStatus',
          description: 'Enter Report repository status',
          type: 'radio',
          options: [
            { label: 'On', value: true },
            { label: 'Off', value: false },
          ],
          validationMessage: 'Please enter Report repository status',
          isRequired: false,
          disabled: false,
          span: 24,
        },
        // {
        //   value: false,
        //   name: 'anonymus',
        //   title: 'Report repository anonymus',
        //   label: 'Report repository anonymus',
        //   translationPath: 'forms.createReportForm.anonymus',
        //   description: 'Enter Report repository anonymus',
        //   type: 'radio',
        //   options: [
        //     { label: 'Yes', value: true },
        //     { label: 'No', value: false },
        //   ],
        //   validationMessage: 'please Enter Report repository anonymus',
        //   isRequired: false,
        //   disabled: false,
        //   span: 24,
        // },
      ],
    },
  ],
};
