import { Form } from '../../../@shared/components/form/@types/form';

const updateUserPassword: Form = {
  submitButtonText: 'userManagement.changePassword',
  groups: [
    {
      fields: [
        {
          title: 'forms.changePassword.newPassword',
          name: 'newPassword',
          label: 'forms.changePassword.newPasswordLabel',
          translationPath: 'forms.changePassword.newPassword',
          type: 'password',
          isRequired: true,
          description: 'forms.changePassword.newPasswordDescription',
          validationMessage: '',
          span: 24,
          value: '',
          minLength: 6,
        },
        {
          title: 'forms.changePassword.newPasswordConfirmation',
          name: 'newPasswordConfirmation',
          label: 'forms.changePassword.newPasswordConfirmation',
          type: 'password',
          translationPath: 'forms.changePassword.newPasswordConfirmation',
          isRequired: true,
          description: 'forms.changePassword.repeatPasswordDescription',
          validationMessage: '',
          span: 24,
          value: '',
        },
      ],
    },
  ],
};

const changeUserPassword: Form = {
  submitButtonText: 'userManagement.changePassword',
  groups: [
    {
      fields: [
        {
          title: 'forms.changeUserPassword.currentPassword',
          name: 'currentPassword',
          label: 'forms.changeUserPassword.currentPasswordLabel',
          type: 'password',
          translationPath: 'forms.changeUserPassword.currentPassword',
          isRequired: true,
          description: 'forms.changeUserPassword.currentPasswordDescription',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          title: 'forms.changeUserPassword.newPassword',
          name: 'newPassword',
          label: 'forms.changeUserPassword.newPasswordLabel',
          type: 'password',
          translationPath: 'forms.changeUserPassword.newPassword',
          isRequired: true,
          description: 'forms.changeUserPassword.newPasswordDescription',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          title: 'forms.changeUserPassword.newPasswordConfirmation',
          name: 'newPasswordConfirmation',
          label: 'forms.changeUserPassword.newPasswordConfirmation',
          type: 'password',
          translationPath: 'forms.changeUserPassword.newPasswordConfirmation',
          isRequired: true,
          description: 'forms.changeUserPassword.repeatPasswordDescription',
          validationMessage: '',
          span: 24,
          value: '',
        },
      ],
    },
  ],
};

const userProfile: Form = {
  layout: 'definition',
  labelWidth: '28%',
  valueAlign: 'left',
  submitButtonText: 'userManagement.saveUser',
  editButtonText: 'userManagement.editUser',
  submitButtonClass: 'right-align-submit',
  groups: [
    {
      title: 'userManagement.personalInformation',
      fields: [
        {
          title: 'forms.userProfile.workID',
          label: 'forms.userProfile.workID',
          name: 'workID',
          type: 'text',
          translationPath: 'forms.userProfile.workID',
          isRequired: false,
          description: 'forms.userProfile.workIDDescription',
          validationMessage: 'forms.userProfile.workIDValidation',
          span: 12,
          value: '',
        },
        {
          title: 'forms.userProfile.email',
          label: 'forms.userProfile.email',
          name: 'email',
          translationPath: 'forms.userProfile.email',
          type: 'text',
          isRequired: true,
          description: 'forms.userProfile.emailDescription',
          validationMessage: 'forms.userProfile.emailValidation',
          span: 12,
          value: '',
        },
        {
          title: 'forms.userProfile.firstName',
          label: 'forms.userProfile.firstName',
          name: 'firstName',
          type: 'text',
          translationPath: 'forms.userProfile.firstName',
          isRequired: true,
          description: 'forms.userProfile.firstNameDescription',
          validationMessage: 'forms.userProfile.firstNameValidation',
          span: 8,
          value: '',
        },
        {
          title: 'forms.userProfile.middleName',
          label: 'forms.userProfile.middleName',
          name: 'middleName',
          type: 'text',
          translationPath: 'forms.userProfile.middleName',
          isRequired: false,
          description: 'forms.userProfile.middleNameDescription',
          validationMessage: 'forms.userProfile.middleNameValidation',
          span: 8,
          value: '',
        },
        {
          title: 'forms.userProfile.lastName',
          label: 'forms.userProfile.lastName',
          name: 'lastName',
          type: 'text',
          translationPath: 'forms.userProfile.lastName',
          isRequired: true,
          description: 'forms.userProfile.lastNameDescription',
          validationMessage: 'forms.userProfile.lastNameValidation',
          span: 8,
          value: '',
        },

        {
          title: 'forms.userProfile.phone',
          label: 'forms.userProfile.phone',
          name: 'phone',
          type: 'text',
          translationPath: 'forms.userProfile.phone',
          isRequired: false,
          description: 'forms.userProfile.phoneDescription',
          validationMessage: 'forms.userProfile.phoneValidation',
          span: 8,
          value: '',
        },

        {
          title: 'forms.userProfile.password',
          label: 'forms.userProfile.password',
          name: 'password',
          type: 'password',
          translationPath: 'forms.userProfile.password',
          isRequired: true,
          description: 'forms.userProfile.passwordDescription',
          validationMessage: 'forms.userProfile.passwordValidation',
          span: 8,
          value: '',
          minLength: 6,
        },
        {
          value: [],
          name: 'roleId',
          translationPath: 'forms.userRolesPermissions.roleId',
          title: 'forms.userRolesPermissions.roles',
          label: 'forms.userRolesPermissions.roles',
          description: 'forms.userRolesPermissions.selectRoles',
          type: 'select',
          mode: 'multiple',
          validationMessage: 'forms.common.requiredField',
          isRequired: true,
          options: [],
          span: 12,
        },
        {
          value: [],
          name: 'departmentId',
          title: 'forms.userProfile.departmentsInstitutions',
          label: 'forms.userProfile.departmentsInstitutions',
          description: 'forms.userProfile.selectDepartmentsInstitutions',
          type: 'select',
          mode: 'multiple',
          validationMessage: 'forms.userProfile.departmentsInstitutionsValidation',
          isRequired: true,
          options: [],
          span: 12,
        },
      ],
    },
  ],
};

const userProfileEdit: Form = {
  layout: 'definition',
  labelWidth: '28%',
  valueAlign: 'left',
  submitButtonText: 'userManagement.saveUser',
  editButtonText: 'userManagement.editUser',
  submitButtonClass: 'right-align-submit',
  groups: [
    {
      title: 'userManagement.personalInformation',
      fields: [
        {
          title: 'forms.userProfileEdit.workID',
          label: 'forms.userProfileEdit.workID',
          name: 'workID',
          translationPath: 'forms.userProfileEdit.workID',
          type: 'text',
          isRequired: false,
          description: 'forms.userProfile.workIDDescription',
          validationMessage: 'forms.userProfile.workIDValidation',
          span: 12,
          value: '',
        },
        {
          title: 'forms.userProfileEdit.email',
          label: 'forms.userProfileEdit.email',
          name: 'email',
          translationPath: 'forms.userProfileEdit.email',
          type: 'text',
          isRequired: true,
          description: 'forms.userProfile.emailDescription',
          validationMessage: 'forms.userProfile.emailValidation',
          span: 12,
          value: '',
        },
        {
          title: 'forms.userProfileEdit.firstName',
          label: 'forms.userProfileEdit.firstName',
          name: 'firstName',
          translationPath: 'forms.userProfileEdit.firstName',
          type: 'text',
          isRequired: true,
          description: 'forms.userProfile.firstNameDescription',
          validationMessage: 'forms.userProfile.firstNameValidation',
          span: 8,
          value: '',
        },
        {
          title: 'forms.userProfileEdit.middleName',
          label: 'forms.userProfileEdit.middleName',
          name: 'middleName',
          translationPath: 'forms.userProfileEdit.middleName',
          type: 'text',
          isRequired: false,
          description: 'forms.userProfile.middleNameDescription',
          validationMessage: 'forms.userProfile.middleNameValidation',
          span: 8,
          value: '',
        },
        {
          title: 'forms.userProfileEdit.lastName',
          label: 'forms.userProfileEdit.lastName',
          name: 'lastName',
          translationPath: 'forms.userProfileEdit.lastName',
          type: 'text',
          isRequired: true,
          description: 'forms.userProfile.lastNameDescription',
          validationMessage: 'forms.userProfile.lastNameValidation',
          span: 8,
          value: '',
        },

        {
          title: 'forms.userProfileEdit.phone',
          label: 'forms.userProfileEdit.phone',
          name: 'phone',
          translationPath: 'forms.userProfileEdit.phone',
          type: 'text',
          isRequired: false,
          description: 'forms.userProfile.phoneDescription',
          validationMessage: 'forms.userProfile.phoneValidation',
          span: 8,
          value: '',
        },
        {
          value: [],
          name: 'roleId',
          translationPath: 'forms.userRolesPermissions.roleId',
          title: 'forms.userRolesPermissions.roles',
          label: 'forms.userRolesPermissions.roles',
          description: 'forms.userRolesPermissions.selectRoles',
          type: 'select',
          mode: 'multiple',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          options: [],
          span: 12,
        },
        {
          value: [],
          name: 'departmentId',
          title: 'forms.userProfile.departmentsInstitutions',
          label: 'forms.userProfile.departmentsInstitutions',
          description: 'forms.userProfile.selectDepartmentsInstitutions',
          type: 'select',
          mode: 'multiple',
          validationMessage: 'forms.userProfile.departmentsInstitutionsValidation',
          isRequired: false,
          options: [],
          span: 12,
        },
      ],
    },
  ],
};

const userRolesPermissions: Form = {
  submitButtonText: 'userManagement.updateRole',
  groups: [
    {
      title: 'userManagement.userRole',
      fields: [
        {
          value: '',
          name: 'roleId',
          translationPath: 'forms.userRolesPermissions.roleId',
          title: 'forms.userRolesPermissions.roleId',
          label: 'forms.userRolesPermissions.roleId',
          description: 'forms.userRolesPermissions.selectUserRole',
          type: 'select',
          validationMessage: 'forms.common.requiredField',
          isRequired: true,
          options: [],
          span: 24,
        },
      ],
    },
  ],
};

export const userForms = {
  changeUserPassword,
  userProfile,
  userRolesPermissions,
  userProfileEdit,
  updateUserPassword,
};
