import { Form } from '../../../@shared/components/form/@types/form';

export const ScriptForm: Form = {
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'forms.scripts.name',
          label: 'forms.scripts.name',
          translationPath: 'forms.scripts.name',
          description: 'forms.scripts.enterName',
          type: 'text',
          validationMessage: 'forms.scripts.nameRequired',
          isRequired: true,
          span: 24,
        },
        {
          value: undefined,
          name: 'scriptText',
          title: 'forms.scripts.excelFile',
          translationPath: 'forms.scripts.excelFile',
          description: 'forms.scripts.excelFile',
          type: 'file',
          span: 24,
          isRequired: true,
        },
        {
          value: '',
          name: 'version',
          title: 'forms.scripts.version',
          label: 'forms.scripts.version',
          translationPath: 'forms.scripts.version',
          description: 'forms.scripts.enterVersion',
          type: 'text',
          validationMessage: 'forms.scripts.versionRequired',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'creator',
          title: 'forms.scripts.creator',
          label: 'forms.scripts.creator',
          translationPath: 'forms.scripts.creator',
          description: 'forms.scripts.enterCreator',
          type: 'text',
          validationMessage: 'forms.scripts.creatorRequired',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'repositoryLink',
          title: 'forms.scripts.repositoryLink',
          label: 'forms.scripts.repositoryLink',
          translationPath: 'forms.scripts.repositoryLink',
          description: 'forms.scripts.enterRepositoryLink',
          type: 'text',
          validationMessage: 'forms.scripts.repositoryLinkRequired',
          isRequired: false,
          span: 24,
        },
      ],
    },
  ],
};

export const UpdateScriptForm: Form = {
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'forms.scripts.name',
          label: 'forms.scripts.name',
          translationPath: 'forms.scripts.name',
          description: 'forms.scripts.enterName',
          type: 'text',
          validationMessage: 'forms.scripts.nameRequired',
          isRequired: true,
          span: 24,
        },
        {
          value: '',
          name: 'version',
          title: 'forms.scripts.version',
          label: 'forms.scripts.version',
          translationPath: 'forms.scripts.version',
          description: 'forms.scripts.enterVersion',
          type: 'text',
          validationMessage: 'forms.scripts.versionRequired',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'creator',
          title: 'forms.scripts.creator',
          label: 'forms.scripts.creator',
          translationPath: 'forms.scripts.creator',
          description: 'forms.scripts.enterCreator',
          type: 'text',
          validationMessage: 'forms.scripts.creatorRequired',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'repositoryLink',
          title: 'forms.scripts.repositoryLink',
          label: 'forms.scripts.repositoryLink',
          translationPath: 'forms.scripts.repositoryLink',
          description: 'forms.scripts.enterRepositoryLink',
          type: 'text',
          validationMessage: 'forms.scripts.repositoryLinkRequired',
          isRequired: false,
          span: 24,
        },
      ],
    },
  ],
};
