import { Form } from '@shared/components/form/@types/form';
import { getNames } from 'i18n-iso-countries';

export const CaregiverForm: Form = {
  layout: 'definition',
  labelWidth: '28%',
  valueAlign: 'left',
  submitButtonText: 'patientsManagement.submitContact',
  editButtonText: 'patientsManagement.submitContact',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'phone',
          title: 'forms.patients.phone',
          label: 'forms.patients.phone',
          translationPath: 'forms.patients.phone',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: true,
          span: 13,
        },
        {
          value: '',
          name: 'firstName',
          title: 'forms.patients.firstName',
          label: 'forms.patients.firstName',
          translationPath: 'forms.patients.firstName',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: true,
          span: 12,
        },
        {
          value: '',
          name: 'middleName',
          title: 'forms.patients.middleName',
          label: 'forms.patients.middleName',
          translationPath: 'forms.patients.middleName',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'lastName',
          title: 'forms.patients.lastName',
          label: 'forms.patients.lastName',
          translationPath: 'forms.patients.lastName',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: true,
          span: 12,
        },
        {
          value: '',
          name: 'email',
          title: 'forms.patients.email',
          label: 'forms.patients.email',
          translationPath: 'forms.patients.email',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: true,
          span: 12,
        },
        {
          value: '',
          name: 'street',
          title: 'forms.patients.street',
          label: 'forms.patients.street',
          translationPath: 'forms.patients.street',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'number',
          title: 'forms.patients.number',
          label: 'forms.patients.number',
          translationPath: 'forms.patients.number',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'apartment',
          title: 'forms.patients.apartment',
          label: 'forms.patients.apartment',
          translationPath: 'forms.patients.apartment',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'place',
          title: 'forms.patients.place',
          label: 'forms.patients.place',
          translationPath: 'forms.patients.place',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'postalCode',
          title: 'forms.patients.postalCode',
          label: 'forms.patients.postalCode',
          translationPath: 'forms.patients.postalCode',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'country',
          title: 'forms.patients.country',
          label: 'forms.patients.country',
          translationPath: 'forms.patients.country',
          description: 'forms.common.enterValue',
          type: 'select',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 12,
          options: Object.entries(getNames('en', { select: 'official' })).map(([value, label]) => ({ label, value })),
        },
        {
          value: '',
          name: 'patientId',
          title: 'forms.patients.linkedPatient',
          label: 'forms.patients.linkedPatient',
          description: 'forms.common.enterValue',
          type: 'search',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'relation',
          title: 'forms.patients.relation',
          label: 'forms.patients.relation',
          translationPath: 'forms.patients.relation',
          description: 'forms.common.enterValue',
          type: 'select',
          options: [
            { label: 'planAssessment.relations.mother', value: 'planAssessment.relations.mother' },
            { label: 'planAssessment.relations.father', value: 'planAssessment.relations.father' },
            { label: 'planAssessment.relations.grandparent', value: 'planAssessment.relations.grandparent' },
            { label: 'planAssessment.relations.uncleAunt', value: 'planAssessment.relations.uncleAunt' },
            { label: 'planAssessment.relations.extendedFamily', value: 'planAssessment.relations.extendedFamily' },
            { label: 'planAssessment.relations.legalGuardian', value: 'planAssessment.relations.legalGuardian' },
            { label: 'planAssessment.relations.familyDoctor', value: 'planAssessment.relations.familyDoctor' },
            { label: 'planAssessment.relations.externalPaediatrician', value: 'planAssessment.relations.externalPaediatrician' },
            { label: 'planAssessment.relations.externalPsychotherapist', value: 'planAssessment.relations.externalPsychotherapist' },
            { label: 'planAssessment.relations.externalPsychologist', value: 'planAssessment.relations.externalPsychologist' },
            { label: 'planAssessment.relations.externalSocialWorker', value: 'planAssessment.relations.externalSocialWorker' },
            { label: 'planAssessment.relations.externalNurse', value: 'planAssessment.relations.externalNurse' },
            { label: 'planAssessment.relations.emergencyDepartment', value: 'planAssessment.relations.emergencyDepartment' },
            { label: 'planAssessment.relations.friend', value: 'planAssessment.relations.friend' },
            { label: 'planAssessment.relations.neighbour', value: 'planAssessment.relations.neighbour' },
            { label: 'planAssessment.relations.teacher', value: 'planAssessment.relations.teacher' },
            { label: 'planAssessment.relations.schoolRepresentative', value: 'planAssessment.relations.schoolRepresentative' },
            { label: 'planAssessment.relations.advisor', value: 'planAssessment.relations.advisor' },
            { label: 'planAssessment.relations.legalAdvisor', value: 'planAssessment.relations.legalAdvisor' },
            { label: 'planAssessment.relations.assistance', value: 'planAssessment.relations.assistance' },
            { label: 'planAssessment.relations.supervisor', value: 'planAssessment.relations.supervisor' },
            { label: 'forms.patients.genderOther', value: 'forms.patients.genderOther' },
          ],
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'emergency',
          title: 'forms.patients.emergencyContacts',
          label: 'forms.patients.emergency',
          translationPath: 'forms.patients.emergency',
          type: 'radio',
          options: [
            { label: 'core.yes', value: true },
            { label: 'core.no', value: false },
          ],
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'note',
          title: 'forms.patients.note',
          label: 'forms.patients.note',
          translationPath: 'forms.patients.note',
          description: 'forms.common.enterValue',
          type: 'textArea',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 24,
        },
        // {
        //   value: '',
        //   name: 'relation',
        //   title: 'forms.patients.relation',
        //   label: 'forms.patients.relation',
        //   translationPath: 'forms.patients.relation',
        //   description: 'forms.common.enterValue',
        //   type: 'select',
        //   options: [
        //     { label: 'planAssessment.relations.mother', value: 'planAssessment.relations.mother' },
        //     { label: 'planAssessment.relations.father', value: 'planAssessment.relations.father' },
        //     { label: 'planAssessment.relations.grandparent', value: 'planAssessment.relations.grandparent' },
        //     { label: 'planAssessment.relations.uncleAunt', value: 'planAssessment.relations.uncleAunt' },
        //     { label: 'planAssessment.relations.extendedFamily', value: 'planAssessment.relations.extendedFamily' },
        //     { label: 'planAssessment.relations.legalGuardian', value: 'planAssessment.relations.legalGuardian' },
        //     { label: 'planAssessment.relations.familyDoctor', value: 'planAssessment.relations.familyDoctor' },
        //     { label: 'planAssessment.relations.externalPaediatrician', value: 'planAssessment.relations.externalPaediatrician' },
        //     { label: 'planAssessment.relations.externalPsychotherapist', value: 'planAssessment.relations.externalPsychotherapist' },
        //     { label: 'planAssessment.relations.externalPsychologist', value: 'planAssessment.relations.externalPsychologist' },
        //     { label: 'planAssessment.relations.externalSocialWorker', value: 'planAssessment.relations.externalSocialWorker' },
        //     { label: 'planAssessment.relations.externalNurse', value: 'planAssessment.relations.externalNurse' },
        //     { label: 'planAssessment.relations.emergencyDepartment', value: 'planAssessment.relations.emergencyDepartment' },
        //     { label: 'planAssessment.relations.friend', value: 'planAssessment.relations.friend' },
        //     { label: 'planAssessment.relations.neighbour', value: 'planAssessment.relations.neighbour' },
        //     { label: 'planAssessment.relations.teacher', value: 'planAssessment.relations.teacher' },
        //     { label: 'planAssessment.relations.schoolRepresentative', value: 'planAssessment.relations.schoolRepresentative' },
        //     { label: 'planAssessment.relations.advisor', value: 'planAssessment.relations.advisor' },
        //     { label: 'planAssessment.relations.legalAdvisor', value: 'planAssessment.relations.legalAdvisor' },
        //     { label: 'planAssessment.relations.assistance', value: 'planAssessment.relations.assistance' },
        //     { label: 'planAssessment.relations.supervisor', value: 'planAssessment.relations.supervisor' },
        //     { label: 'forms.patients.genderOther', value: 'forms.patients.genderOther' }
        //   ],
        //   validationMessage: 'forms.common.requiredField',
        //   isRequired: true,
        //   span: 24
        // },
        // {
        //   value: '',
        //   name: 'emergencyContact',
        //   title: 'forms.patients.emergencyContacts',
        //   label: 'forms.patients.emergency',
        //   translationPath: 'forms.patients.emergency',
        //   type: 'radio',
        //   options:[
        //     {label: 'core.yes', value: true},
        //     {label: 'core.no', value: false}
        //   ],
        //   validationMessage: 'forms.common.requiredField',
        //   isRequired: false,
        //   span: 24
        // },
        // {
        //   value: '',
        //   name: 'note',
        //   title: 'forms.patients.note',
        //   label: 'forms.patients.note',
        //   translationPath: 'forms.patients.note',
        //   description: 'forms.common.enterValue',
        //   type: 'textArea',
        //   validationMessage: 'forms.common.requiredField',
        //   isRequired: false,
        //   span: 24
        // }
      ],
    },
  ],
};
