import { Form } from '@shared/components/form/@types/form';

export const InformantForm: Form = {
  submitButtonText: 'patientsManagement.submitInformant',
  editButtonText: 'patientsManagement.submitInformant',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'firstName',
          title: 'forms.patients.firstName',
          label: 'forms.patients.firstName',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'middleName',
          title: 'forms.patients.middleName',
          label: 'forms.patients.middleName',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'lastName',
          title: 'forms.patients.lastName',
          label: 'forms.patients.lastName',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'phone',
          title: 'forms.patients.phone',
          label: 'forms.patients.phone',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'email',
          title: 'forms.patients.email',
          label: 'forms.patients.email',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'address',
          title: 'forms.patients.address',
          label: 'forms.patients.address',
          description: 'forms.common.enterValue',
          type: 'text',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'patientId',
          title: 'forms.patients.patient',
          label: 'forms.patients.patient',
          description: 'forms.common.enterValue',
          type: 'search',
          validationMessage: 'forms.common.requiredField',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'relationshipTypeId',
          title: 'forms.patients.relationshipType',
          label: 'forms.patients.relationshipType',
          description: 'forms.common.enterValue',
          type: 'select',
          validationMessage: 'forms.common.requiredField',
          isRequired: false,
          span: 24,
          options: [],
        },
      ],
    },
  ],
};
