import { Form } from '@shared/components/form/@types/form';
import { Field } from '@shared/components/form/@types/field';
import { getNames } from 'i18n-iso-countries';

const informationFields: Field[] = [
  {
    value: '',
    name: 'firstName',
    title: 'forms.patients.firstName',
    label: 'forms.patients.firstName',
    translationPath: 'forms.patients.firstName',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: true,
    span: 8,
  },
  {
    value: '',
    name: 'middleName',
    title: 'forms.patients.middleName',
    label: 'forms.patients.middleName',
    translationPath: 'forms.patients.middleName',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'lastName',
    title: 'forms.patients.lastName',
    label: 'forms.patients.lastName',
    translationPath: 'forms.patients.lastName',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: true,
    span: 8,
  },
  {
    value: '',
    title: 'forms.patients.birthDate',
    name: 'birthDate',
    label: 'forms.patients.birthDate',
    translationPath: 'forms.patients.birthDate',
    description: 'forms.common.enterValue',
    type: 'date',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'gender',
    title: 'forms.patients.gender',
    label: 'forms.patients.gender',
    translationPath: 'forms.patients.gender',
    description: 'forms.common.enterValue',
    type: 'select',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    options: [
      { label: 'forms.patients.genderMale', value: 'male' },
      { label: 'forms.patients.genderFemale', value: 'female' },
      { label: 'forms.patients.genderOther', value: 'other' },
    ],
    span: 8,
  },
];

const addressFields: Field[] = [
  {
    value: '',
    name: 'addressStreet',
    title: 'forms.patients.street',
    label: 'forms.patients.street',
    translationPath: 'forms.patients.street',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressNumber',
    title: 'forms.patients.number',
    label: 'forms.patients.number',
    translationPath: 'forms.patients.addressNumber',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressApartment',
    title: 'forms.patients.apartment',
    label: 'forms.patients.apartment',
    translationPath: 'forms.patients.addressApartment',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressPlace',
    title: 'forms.patients.place',
    label: 'forms.patients.place',
    translationPath: 'forms.patients.addressPlace',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressPostalCode',
    title: 'forms.patients.postalCode',
    label: 'forms.patients.postalCode',
    translationPath: 'forms.patients.addressPostalCode',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressCountryCode',
    title: 'forms.patients.country',
    label: 'forms.patients.country',
    translationPath: 'forms.patients.addressCountryCode',
    description: 'forms.common.enterValue',
    type: 'select',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    span: 8,
    options: Object.entries(getNames('en', { select: 'official' })).map(([value, label]) => ({ label, value })),
  },
];

const contactFields: Field[] = [
  {
    value: '',
    name: 'email',
    title: 'forms.patients.email',
    label: 'forms.patients.email',
    translationPath: 'forms.patients.email',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: true,
    span: 8,
  },
  {
    value: '',
    name: 'phone',
    title: 'forms.patients.phone',
    label: 'forms.patients.phone',
    translationPath: 'forms.patients.phone',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'phone2',
    title: 'forms.patients.phone2',
    label: 'forms.patients.phone2',
    translationPath: 'forms.patients.phone2',
    description: 'forms.common.enterValue',
    type: 'text',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    span: 8,
  },
];

const emergencyContactFields: Field[] = [
  {
    value: '',
    name: 'emergencyContacts',
    title: 'forms.patients.emergencyContacts',
    label: 'forms.patients.emergencyContacts',
    translationPath: 'forms.patients.emergencyContacts',
    description: 'forms.common.enterValue',
    type: 'array',
    validationMessage: 'forms.common.requiredField',
    isRequired: false,
    span: 24,
    rows: [],
    children: [
      {
        value: '',
        name: 'id',
        title: 'forms.patients.id',
        label: 'forms.patients.id',
        type: 'text',
        validationMessage: '',
        isRequired: false,
        span: 0,
        hidden: true,
      },
      {
        value: '',
        name: 'caregiverId',
        title: 'forms.patients.caregiverId',
        label: 'forms.patients.caregiverId',
        type: 'text',
        validationMessage: '',
        isRequired: false,
        span: 0,
        hidden: true,
      },
      {
        value: '',
        name: 'firstName',
        title: 'forms.patients.firstName',
        label: 'forms.patients.firstName',
        translationPath: 'forms.patients.firstName',
        description: 'forms.common.enterValue',
        type: 'text',
        validationMessage: 'forms.common.requiredField',
        isRequired: false,
        span: 8,
      },
      {
        value: '',
        name: 'middleName',
        title: 'forms.patients.middleName',
        label: 'forms.patients.middleName',
        translationPath: 'forms.patients.middleName',
        description: 'forms.common.enterValue',
        type: 'text',
        validationMessage: 'forms.common.requiredField',
        isRequired: false,
        span: 8,
      },
      {
        value: '',
        name: 'lastName',
        title: 'forms.patients.lastName',
        label: 'forms.patients.lastName',
        translationPath: 'forms.patients.lastName',
        description: 'forms.common.enterValue',
        type: 'text',
        validationMessage: 'forms.common.requiredField',
        isRequired: false,
        span: 8,
      },
      {
        value: '',
        name: 'email',
        title: 'forms.patients.email',
        label: 'forms.patients.email',
        translationPath: 'forms.patients.email',
        description: 'forms.common.enterValue',
        type: 'text',
        validationMessage: 'forms.common.requiredField',
        isRequired: false,
        span: 12,
      },
      {
        value: '',
        name: 'phone',
        title: 'forms.patients.phone',
        label: 'forms.patients.phone',
        translationPath: 'forms.patients.phone',
        description: 'forms.common.enterValue',
        type: 'text',
        validationMessage: 'forms.common.requiredField',
        isRequired: false,
        span: 12,
      },
      {
        value: false,
        name: 'createCaregiver',
        title: 'forms.patients.createCaregiver',
        label: 'forms.patients.isCaregiver',
        description: 'forms.common.enterValue',
        type: 'radio',
        options: [
          { label: 'core.yes', value: true },
          { label: 'core.no', value: false },
        ],
        validationMessage: '',
        isRequired: false,
        span: 24,
      },
    ],
  },
];

const getForm = (createMode: boolean): Form => {
  return {
    layout: 'definition',
    labelWidth: '28%',
    valueAlign: 'left',
    submitButtonText: 'patientsManagement.savePatient',
    editButtonText: 'patientsManagement.editPatient',
    submitButtonClass: 'right-align-submit',
    groups: [
      {
        title: 'forms.patients.patientInformation',
        translationPath: 'forms.patients.patientInformation',
        fields: informationFields,
      },
      {
        title: 'forms.patients.patientAddress',
        translationPath: 'forms.patients.patientAddress',
        fields: addressFields,
      },
      {
        title: 'forms.patients.patientContact',
        translationPath: 'forms.patients.patientContact',
        fields: contactFields,
      },
      {
        title: 'forms.patients.emergencyContacts',
        translationPath: 'forms.patients.emergencyContacts',
        fields: emergencyContactFields,
      },
    ],
  };
};

export const PatientCreateForm = getForm(true);
export const PatientUpdateForm = getForm(false);
