import { Form } from '../../../../@shared/components/form/@types/form';
import { Setting } from '../../@types/setting';

const general: Form & { groups: { fields: { name: keyof Setting }[] }[] } = {
  submitButtonText: 'core.save',
  groups: [
    {
      fields: [
        {
          title: 'form.system.systemLocale',
          name: 'systemLocale',
          translationPath: 'form.system.systemLocale',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'systemSettings.systemLocaleDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'form.system.systemTimezone',
          name: 'systemTimezone',
          translationPath: 'form.system.systemTimezone',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'systemSettings.systemTimezoneDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'form.system.dateFormat',
          name: 'dateFormat',
          translationPath: 'form.system.dateFormat',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'systemSettings.dateFormatDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'form.system.timeFormat',
          name: 'timeFormat',
          translationPath: 'form.system.timeFormat',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'systemSettings.timeFormatDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'form.system.dateTimeFormat',
          name: 'dateTimeFormat',
          translationPath: 'form.system.dateTimeFormat',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'systemSettings.dateTimeFormatDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'form.system.passwordLifeTimeInDays',
          name: 'passwordLifeTimeInDays',
          translationPath: 'form.system.passwordLifeTimeInDays',
          type: 'number',
          isRequired: false,
          description: 'systemSettings.passwordLifeTimeDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'form.system.passwordReUseCutoffInDays',
          name: 'passwordReUseCutoffInDays',
          translationPath: 'form.system.passwordReUseCutoffInDays',
          type: 'number',
          isRequired: false,
          description: 'systemSettings.passwordReuseCutoffDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'form.system.notificationLogRetentionDays',
          name: 'notificationLogRetentionDays',
          translationPath: 'form.system.notificationLogRetentionDays',
          type: 'number',
          isRequired: false,
          description: 'systemSettings.notificationLogRetentionDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 365,
        },
        {
          title: 'form.system.accessTokenRetentionDays',
          name: 'accessTokenRetentionDays',
          translationPath: 'form.system.accessTokenRetentionDays',
          type: 'number',
          isRequired: false,
          description: 'systemSettings.accessTokenRetentionDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 30,
        },
        {
          title: 'form.system.maxLoginAttempts',
          name: 'maxLoginAttempts',
          translationPath: 'form.system.maxLoginAttempts',
          type: 'number',
          isRequired: false,
          description: 'systemSettings.maxLoginAttemptsDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: undefined,
        },
        {
          title: 'form.system.evaluationAutomationRunRetentionDays',
          translationPath: 'form.system.evaluationAutomationRunRetentionDays',
          name: 'evaluationAutomationRunRetentionDays',
          type: 'number',
          isRequired: false,
          description: 'systemSettings.evaluationAutomationRunRetentionDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 365,
        },
        {
          title: 'form.system.treatmentFinalizationUndoWindowDays',
          translationPath: 'form.system.treatmentFinalizationUndoWindowDays',
          name: 'treatmentFinalizationUndoWindowDays',
          type: 'number',
          isRequired: false,
          description: 'systemSettings.treatmentFinalizationUndoWindowDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 30,
        },
        {
          title: 'form.system.patientCaseManagerAssignableHierarchyRank',
          translationPath: 'form.system.patientCaseManagerAssignableHierarchyRank',
          name: 'patientCaseManagerAssignableHierarchyRank',
          type: 'number',
          isRequired: false,
          description: 'systemSettings.patientCaseManagerAssignableHierarchyRankDescription',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 500,
        },
      ],
    },
  ],
};

export const settingsForms = {
  general,
};
