import { Form } from '../../../../@shared/components/form/@types/form';
import { Setting } from '../../@types/setting';

const general: Form & { groups: { fields: { name: keyof Setting }[] }[] } = {
  submitButtonText: 'Save',
  groups: [
    {
      fields: [
        {
          title: 'Set system locale',
          name: 'systemLocale',
          translationPath: 'form.system.systemLocale',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'Define el idioma regional usado para nombres de meses, dias y formatos localizados.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Set system time zone',
          name: 'systemTimezone',
          translationPath: 'form.system.systemTimezone',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'Define la zona horaria institucional para mostrar y programar fechas en PSIRA.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Set date format',
          name: 'dateFormat',
          translationPath: 'form.system.dateFormat',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'Formato usado para mostrar fechas cuando no se necesita hora.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Set time format',
          name: 'timeFormat',
          translationPath: 'form.system.timeFormat',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'Formato usado para mostrar horas.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Set date and time format',
          name: 'dateTimeFormat',
          translationPath: 'form.system.dateTimeFormat',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'Formato usado cuando una fecha se muestra junto con la hora. Si queda en el valor base, hereda fecha y hora.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Password life time (In Days)',
          name: 'passwordLifeTimeInDays',
          translationPath: 'form.system.passwordLifeTimeInDays',
          type: 'number',
          isRequired: false,
          description: 'Cantidad de dias de vigencia de una contraseña antes de exigir cambio.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Password re-use cut off(In Days)',
          name: 'passwordReUseCutoffInDays',
          translationPath: 'form.system.passwordReUseCutoffInDays',
          type: 'number',
          isRequired: false,
          description: 'Dias durante los cuales no se puede reutilizar una contraseña anterior. Los hashes mas viejos se eliminan automaticamente.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Notification log retention (days)',
          name: 'notificationLogRetentionDays',
          translationPath: 'form.system.notificationLogRetentionDays',
          type: 'number',
          isRequired: false,
          description: 'Dias que se conservan los logs tecnicos de notificaciones enviadas, fallidas u omitidas.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 365,
        },
        {
          title: 'Access token retention (days)',
          name: 'accessTokenRetentionDays',
          translationPath: 'form.system.accessTokenRetentionDays',
          type: 'number',
          isRequired: false,
          description: 'Dias que se conservan tokens vencidos o revocados antes de eliminarlos.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 30,
        },
        {
          title: 'Max login attempts',
          name: 'maxLoginAttempts',
          translationPath: 'form.system.maxLoginAttempts',
          type: 'number',
          isRequired: false,
          description: 'Intentos fallidos permitidos antes de bloquear temporalmente el login.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: undefined,
        },
        {
          title: 'Automation history retention (days)',
          name: 'evaluationAutomationRunRetentionDays',
          type: 'number',
          isRequired: false,
          description: 'Cantidad de dias que se conserva el historial de ejecucion de automatizaciones.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 365,
        },
        {
          title: 'Treatment finalization undo window (days)',
          name: 'treatmentFinalizationUndoWindowDays',
          type: 'number',
          isRequired: false,
          description: 'Dias durante los cuales se puede anular una finalizacion de tratamiento o supervision.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 30,
        },
        {
          title: 'Case manager hierarchy rank cutoff',
          name: 'patientCaseManagerAssignableHierarchyRank',
          type: 'number',
          isRequired: false,
          description: 'Jerarquia numerica maxima que puede asignarse como administrador del caso.',
          showDescription: true,
          validationMessage: '',
          span: 8,
          value: 500,
        },
      ],
    },
  ],
};

export const settingsForms = {
  general,
};
