export enum PermissionKey {
  USERS_VIEW_ALL = 'users.view.all',
  USERS_VIEW_DEPARTMENT = 'users.view.department',
  USERS_VIEW_DEPARTMENT_HIERARCHY = 'users.view.department-hierarchy',
  USERS_CREATE_ALL = 'users.create.all',
  USERS_CREATE_DEPARTMENT = 'users.create.department',
  USERS_CREATE_DEPARTMENT_HIERARCHY = 'users.create.department-hierarchy',
  USERS_EDIT_ALL = 'users.edit.all',
  USERS_EDIT_DEPARTMENT = 'users.edit.department',
  USERS_EDIT_DEPARTMENT_HIERARCHY = 'users.edit.department-hierarchy',
  USERS_DELETE_ALL = 'users.delete.all',
  USERS_DELETE_DEPARTMENT = 'users.delete.department',
  USERS_DELETE_DEPARTMENT_HIERARCHY = 'users.delete.department-hierarchy',
  USERS_RESTORE_ALL = 'users.restore.all',
  USERS_RESTORE_DEPARTMENT = 'users.restore.department',
  USERS_RESTORE_DEPARTMENT_HIERARCHY = 'users.restore.department-hierarchy',

  PATIENTS_VIEW_ALL = 'patients.view.all',
  PATIENTS_VIEW_DEPARTMENT = 'patients.view.department',
  PATIENTS_VIEW_ASSIGNED = 'patients.view.assigned',
  PATIENTS_CREATE_ALL = 'patients.create.all',
  PATIENTS_CREATE_DEPARTMENT = 'patients.create.department',
  PATIENTS_CREATE_ASSIGNED = 'patients.create.assigned',
  PATIENTS_EDIT_ALL = 'patients.edit.all',
  PATIENTS_EDIT_DEPARTMENT = 'patients.edit.department',
  PATIENTS_EDIT_ASSIGNED = 'patients.edit.assigned',
  PATIENTS_DELETE_ALL = 'patients.delete.all',
  PATIENTS_DELETE_DEPARTMENT = 'patients.delete.department',
  PATIENTS_DELETE_ASSIGNED = 'patients.delete.assigned',
  PATIENTS_ARCHIVE_ALL = 'patients.archive.all',
  PATIENTS_ARCHIVE_DEPARTMENT = 'patients.archive.department',
  PATIENTS_ARCHIVE_ASSIGNED = 'patients.archive.assigned',
  PATIENTS_RESTORE_ALL = 'patients.restore.all',
  PATIENTS_RESTORE_DEPARTMENT = 'patients.restore.department',
  PATIENTS_RESTORE_ASSIGNED = 'patients.restore.assigned',

  THERAPISTS_VIEW_ALL = 'therapists.view.all',
  THERAPISTS_VIEW_DEPARTMENT = 'therapists.view.department',
  THERAPISTS_VIEW_ASSIGNED = 'therapists.view.assigned',
  THERAPISTS_CREATE_ALL = 'therapists.create.all',
  THERAPISTS_CREATE_DEPARTMENT = 'therapists.create.department',
  THERAPISTS_CREATE_ASSIGNED = 'therapists.create.assigned',
  THERAPISTS_EDIT_ALL = 'therapists.edit.all',
  THERAPISTS_EDIT_DEPARTMENT = 'therapists.edit.department',
  THERAPISTS_EDIT_ASSIGNED = 'therapists.edit.assigned',
  THERAPISTS_DELETE_ALL = 'therapists.delete.all',
  THERAPISTS_DELETE_DEPARTMENT = 'therapists.delete.department',
  THERAPISTS_DELETE_ASSIGNED = 'therapists.delete.assigned',

  SUPERVISORS_VIEW_ALL = 'supervisors.view.all',
  SUPERVISORS_VIEW_DEPARTMENT = 'supervisors.view.department',
  SUPERVISORS_CREATE_ALL = 'supervisors.create.all',
  SUPERVISORS_CREATE_DEPARTMENT = 'supervisors.create.department',
  SUPERVISORS_EDIT_ALL = 'supervisors.edit.all',
  SUPERVISORS_EDIT_DEPARTMENT = 'supervisors.edit.department',
  SUPERVISORS_DELETE_ALL = 'supervisors.delete.all',
  SUPERVISORS_DELETE_DEPARTMENT = 'supervisors.delete.department',

  CAREGIVERS_VIEW_ALL = 'caregivers.view.all',
  CAREGIVERS_VIEW_DEPARTMENT = 'caregivers.view.department',
  CAREGIVERS_VIEW_ASSIGNED = 'caregivers.view.assigned',
  CAREGIVERS_CREATE_ALL = 'caregivers.create.all',
  CAREGIVERS_CREATE_DEPARTMENT = 'caregivers.create.department',
  CAREGIVERS_CREATE_ASSIGNED = 'caregivers.create.assigned',
  CAREGIVERS_EDIT_ALL = 'caregivers.edit.all',
  CAREGIVERS_EDIT_DEPARTMENT = 'caregivers.edit.department',
  CAREGIVERS_EDIT_ASSIGNED = 'caregivers.edit.assigned',
  CAREGIVERS_DELETE_ALL = 'caregivers.delete.all',
  CAREGIVERS_DELETE_DEPARTMENT = 'caregivers.delete.department',
  CAREGIVERS_DELETE_ASSIGNED = 'caregivers.delete.assigned',

  CLINICAL_VIEW_ALL = 'clinical.view.all',
  CLINICAL_VIEW_DEPARTMENT = 'clinical.view.department',
  CLINICAL_VIEW_ASSIGNED = 'clinical.view.assigned',
  CLINICAL_CREATE_ALL = 'clinical.create.all',
  CLINICAL_CREATE_DEPARTMENT = 'clinical.create.department',
  CLINICAL_CREATE_ASSIGNED = 'clinical.create.assigned',
  CLINICAL_EDIT_ALL = 'clinical.edit.all',
  CLINICAL_EDIT_DEPARTMENT = 'clinical.edit.department',
  CLINICAL_EDIT_ASSIGNED = 'clinical.edit.assigned',
  CLINICAL_DELETE_ALL = 'clinical.delete.all',
  CLINICAL_DELETE_DEPARTMENT = 'clinical.delete.department',
  CLINICAL_DELETE_ASSIGNED = 'clinical.delete.assigned',

  ASSESSMENTS_VIEW_ALL = 'assessments.view.all',
  ASSESSMENTS_VIEW_DEPARTMENT = 'assessments.view.department',
  ASSESSMENTS_VIEW_ASSIGNED = 'assessments.view.assigned',
  ASSESSMENTS_CREATE_ALL = 'assessments.create.all',
  ASSESSMENTS_CREATE_DEPARTMENT = 'assessments.create.department',
  ASSESSMENTS_CREATE_ASSIGNED = 'assessments.create.assigned',
  ASSESSMENTS_EDIT_ALL = 'assessments.edit.all',
  ASSESSMENTS_EDIT_DEPARTMENT = 'assessments.edit.department',
  ASSESSMENTS_EDIT_ASSIGNED = 'assessments.edit.assigned',
  ASSESSMENTS_DELETE_ALL = 'assessments.delete.all',
  ASSESSMENTS_DELETE_DEPARTMENT = 'assessments.delete.department',
  ASSESSMENTS_DELETE_ASSIGNED = 'assessments.delete.assigned',
  ASSESSMENTS_ARCHIVE_ALL = 'assessments.archive.all',
  ASSESSMENTS_ARCHIVE_DEPARTMENT = 'assessments.archive.department',
  ASSESSMENTS_ARCHIVE_ASSIGNED = 'assessments.archive.assigned',
  ASSESSMENTS_RESTORE_ALL = 'assessments.restore.all',
  ASSESSMENTS_RESTORE_DEPARTMENT = 'assessments.restore.department',
  ASSESSMENTS_RESTORE_ASSIGNED = 'assessments.restore.assigned',
  ASSESSMENTS_ASSIGN_ALL = 'assessments.assign.all',
  ASSESSMENTS_ASSIGN_DEPARTMENT = 'assessments.assign.department',
  ASSESSMENTS_ASSIGN_ASSIGNED = 'assessments.assign.assigned',

  QUESTIONNAIRES_VIEW_ALL = 'questionnaires.view.all',
  QUESTIONNAIRES_VIEW_DEPARTMENT = 'questionnaires.view.department',
  QUESTIONNAIRES_CREATE_ALL = 'questionnaires.create.all',
  QUESTIONNAIRES_CREATE_DEPARTMENT = 'questionnaires.create.department',
  QUESTIONNAIRES_EDIT_ALL = 'questionnaires.edit.all',
  QUESTIONNAIRES_EDIT_DEPARTMENT = 'questionnaires.edit.department',
  QUESTIONNAIRES_DELETE_ALL = 'questionnaires.delete.all',
  QUESTIONNAIRES_DELETE_DEPARTMENT = 'questionnaires.delete.department',

  QUESTIONNAIRE_BUNDLES_VIEW_ALL = 'questionnaire-bundles.view.all',
  QUESTIONNAIRE_BUNDLES_VIEW_DEPARTMENT = 'questionnaire-bundles.view.department',
  QUESTIONNAIRE_BUNDLES_CREATE_ALL = 'questionnaire-bundles.create.all',
  QUESTIONNAIRE_BUNDLES_CREATE_DEPARTMENT = 'questionnaire-bundles.create.department',
  QUESTIONNAIRE_BUNDLES_EDIT_ALL = 'questionnaire-bundles.edit.all',
  QUESTIONNAIRE_BUNDLES_EDIT_DEPARTMENT = 'questionnaire-bundles.edit.department',
  QUESTIONNAIRE_BUNDLES_DELETE_ALL = 'questionnaire-bundles.delete.all',
  QUESTIONNAIRE_BUNDLES_DELETE_DEPARTMENT = 'questionnaire-bundles.delete.department',

  EVALUATION_SCHEMES_VIEW_ALL = 'evaluation-schemes.view.all',
  EVALUATION_SCHEMES_VIEW_DEPARTMENT = 'evaluation-schemes.view.department',
  EVALUATION_SCHEMES_CREATE_ALL = 'evaluation-schemes.create.all',
  EVALUATION_SCHEMES_CREATE_DEPARTMENT = 'evaluation-schemes.create.department',
  EVALUATION_SCHEMES_EDIT_ALL = 'evaluation-schemes.edit.all',
  EVALUATION_SCHEMES_EDIT_DEPARTMENT = 'evaluation-schemes.edit.department',
  EVALUATION_SCHEMES_DELETE_ALL = 'evaluation-schemes.delete.all',
  EVALUATION_SCHEMES_DELETE_DEPARTMENT = 'evaluation-schemes.delete.department',

  RANDOMIZATIONS_VIEW_ALL = 'randomizations.view.all',
  RANDOMIZATIONS_VIEW_DEPARTMENT = 'randomizations.view.department',
  RANDOMIZATIONS_CREATE_ALL = 'randomizations.create.all',
  RANDOMIZATIONS_CREATE_DEPARTMENT = 'randomizations.create.department',
  RANDOMIZATIONS_EDIT_ALL = 'randomizations.edit.all',
  RANDOMIZATIONS_EDIT_DEPARTMENT = 'randomizations.edit.department',
  RANDOMIZATIONS_DELETE_ALL = 'randomizations.delete.all',
  RANDOMIZATIONS_DELETE_DEPARTMENT = 'randomizations.delete.department',

  AUTOMATIONS_VIEW_ALL = 'automations.view.all',
  AUTOMATIONS_VIEW_DEPARTMENT = 'automations.view.department',
  AUTOMATIONS_CREATE_ALL = 'automations.create.all',
  AUTOMATIONS_CREATE_DEPARTMENT = 'automations.create.department',
  AUTOMATIONS_EDIT_ALL = 'automations.edit.all',
  AUTOMATIONS_EDIT_DEPARTMENT = 'automations.edit.department',
  AUTOMATIONS_DELETE_ALL = 'automations.delete.all',
  AUTOMATIONS_DELETE_DEPARTMENT = 'automations.delete.department',
  AUTOMATIONS_TEST_ALL = 'automations.test.all',
  AUTOMATIONS_TEST_DEPARTMENT = 'automations.test.department',

  NOTIFICATIONS_VIEW_ALL = 'notifications.view.all',
  NOTIFICATIONS_VIEW_DEPARTMENT = 'notifications.view.department',
  NOTIFICATIONS_CREATE_ALL = 'notifications.create.all',
  NOTIFICATIONS_CREATE_DEPARTMENT = 'notifications.create.department',
  NOTIFICATIONS_EDIT_ALL = 'notifications.edit.all',
  NOTIFICATIONS_EDIT_DEPARTMENT = 'notifications.edit.department',
  NOTIFICATIONS_DELETE_ALL = 'notifications.delete.all',
  NOTIFICATIONS_DELETE_DEPARTMENT = 'notifications.delete.department',
  NOTIFICATION_LOGS_VIEW_ALL = 'notification-logs.view.all',
  NOTIFICATION_LOGS_VIEW_DEPARTMENT = 'notification-logs.view.department',

  MAIL_TEMPLATES_VIEW_ALL = 'mail-templates.view.all',
  MAIL_TEMPLATES_VIEW_DEPARTMENT = 'mail-templates.view.department',
  MAIL_TEMPLATES_CREATE_ALL = 'mail-templates.create.all',
  MAIL_TEMPLATES_CREATE_DEPARTMENT = 'mail-templates.create.department',
  MAIL_TEMPLATES_EDIT_ALL = 'mail-templates.edit.all',
  MAIL_TEMPLATES_EDIT_DEPARTMENT = 'mail-templates.edit.department',
  MAIL_TEMPLATES_DELETE_ALL = 'mail-templates.delete.all',
  MAIL_TEMPLATES_DELETE_DEPARTMENT = 'mail-templates.delete.department',

  INFORMED_CONSENT_MODELS_VIEW_ALL = 'informed-consent-models.view.all',
  INFORMED_CONSENT_MODELS_VIEW_DEPARTMENT = 'informed-consent-models.view.department',
  INFORMED_CONSENT_MODELS_CREATE_ALL = 'informed-consent-models.create.all',
  INFORMED_CONSENT_MODELS_CREATE_DEPARTMENT = 'informed-consent-models.create.department',
  INFORMED_CONSENT_MODELS_EDIT_ALL = 'informed-consent-models.edit.all',
  INFORMED_CONSENT_MODELS_EDIT_DEPARTMENT = 'informed-consent-models.edit.department',
  INFORMED_CONSENT_MODELS_DELETE_ALL = 'informed-consent-models.delete.all',
  INFORMED_CONSENT_MODELS_DELETE_DEPARTMENT = 'informed-consent-models.delete.department',

  INFORMED_CONSENT_MANAGEMENT_VIEW_ALL = 'informed-consent-management.view.all',
  INFORMED_CONSENT_MANAGEMENT_VIEW_DEPARTMENT = 'informed-consent-management.view.department',
  INFORMED_CONSENT_MANAGEMENT_CREATE_ALL = 'informed-consent-management.create.all',
  INFORMED_CONSENT_MANAGEMENT_CREATE_DEPARTMENT = 'informed-consent-management.create.department',
  INFORMED_CONSENT_MANAGEMENT_EDIT_ALL = 'informed-consent-management.edit.all',
  INFORMED_CONSENT_MANAGEMENT_EDIT_DEPARTMENT = 'informed-consent-management.edit.department',
  INFORMED_CONSENT_MANAGEMENT_DELETE_ALL = 'informed-consent-management.delete.all',
  INFORMED_CONSENT_MANAGEMENT_DELETE_DEPARTMENT = 'informed-consent-management.delete.department',

  INFORMED_CONSENT_RESPONSES_VIEW_ALL = 'informed-consent-responses.view.all',
  INFORMED_CONSENT_RESPONSES_VIEW_DEPARTMENT = 'informed-consent-responses.view.department',
  INFORMED_CONSENT_RESPONSES_VIEW_ASSIGNED = 'informed-consent-responses.view.assigned',
  INFORMED_CONSENT_RESPONSES_REVIEW_ALL = 'informed-consent-responses.review.all',
  INFORMED_CONSENT_RESPONSES_REVIEW_DEPARTMENT = 'informed-consent-responses.review.department',
  INFORMED_CONSENT_RESPONSES_REVIEW_ASSIGNED = 'informed-consent-responses.review.assigned',

  REPORTS_VIEW_ALL = 'reports.view.all',
  REPORTS_VIEW_DEPARTMENT = 'reports.view.department',
  REPORTS_VIEW_ASSIGNED = 'reports.view.assigned',
  REPORTS_CREATE_ALL = 'reports.create.all',
  REPORTS_CREATE_DEPARTMENT = 'reports.create.department',
  REPORTS_CREATE_ASSIGNED = 'reports.create.assigned',
  REPORTS_EDIT_ALL = 'reports.edit.all',
  REPORTS_EDIT_DEPARTMENT = 'reports.edit.department',
  REPORTS_EDIT_ASSIGNED = 'reports.edit.assigned',
  REPORTS_DELETE_ALL = 'reports.delete.all',
  REPORTS_DELETE_DEPARTMENT = 'reports.delete.department',
  REPORTS_DELETE_ASSIGNED = 'reports.delete.assigned',

  DEPARTMENTS_VIEW_ALL = 'departments.view.all',
  DEPARTMENTS_CREATE_ALL = 'departments.create.all',
  DEPARTMENTS_EDIT_ALL = 'departments.edit.all',
  DEPARTMENTS_DELETE_ALL = 'departments.delete.all',
  ROLES_VIEW_ALL = 'roles.view.all',
  ROLES_VIEW_DEPARTMENT_HIERARCHY = 'roles.view.department-hierarchy',
  ROLES_CREATE_ALL = 'roles.create.all',
  ROLES_CREATE_DEPARTMENT_HIERARCHY = 'roles.create.department-hierarchy',
  ROLES_EDIT_ALL = 'roles.edit.all',
  ROLES_EDIT_DEPARTMENT_HIERARCHY = 'roles.edit.department-hierarchy',
  ROLES_DELETE_ALL = 'roles.delete.all',
  ROLES_DELETE_DEPARTMENT_HIERARCHY = 'roles.delete.department-hierarchy',
  PERMISSIONS_VIEW_ALL = 'permissions.view.all',
  PERMISSIONS_VIEW_DEPARTMENT_HIERARCHY = 'permissions.view.department-hierarchy',
  PERMISSIONS_ASSIGN_ALL = 'permissions.assign.all',
  PERMISSIONS_ASSIGN_DEPARTMENT_HIERARCHY = 'permissions.assign.department-hierarchy',
  SETTINGS_VIEW_ALL = 'settings.view.all',
  SETTINGS_EDIT_ALL = 'settings.edit.all',
  SYSTEM_VIEW_ALL = 'system.view.all',
  SYSTEM_EDIT_ALL = 'system.edit.all',
}

export const isPermissionKey = (key: any): key is PermissionKey => {
  return Object.values(PermissionKey).includes(key);
};

export const isPermissionKeyArray = (arr: any): arr is PermissionKey[] => {
  return typeof arr === 'object' && Object.values(arr).every((key) => isPermissionKey(key));
};
